### ISSUE TITLE
Dynamic receiver application ID

### ISSUE THREAD

**Issue by canadianeagle** [AnteWall/react-cast-sender#9]
Hello AnteWall,

First off, thanks for making this - I've been looking for something like this for a while and this is the first one that works and isn't abandoned.

I have lots of questions, but the first one:
**How do I get a dynamic Chromecast ID?**
Basically, in a production app, I shouldn't have to manually enter the device/receiver ID so any user can cast to their device.
Is there any way to do this without having to manually provide a value to the **receiverApplicationId** prop?

Also, would I be able to cast/mirror my app/screen using this? Strange request but it's worth asking :)

Thanks :)

**Comment by AnteWall** [comment]
I haven't worked with Chromecast for a while now but if i remember correctly cast API dont support manually changing the receiver ID (it's why i don't have so you can change the ID on the demo site). Could probably add some kind of Component around that mounts/unmounts the provider depending on the cast id but nothing we support in the lib due to chromecast restrictions
